name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/app || git clone https://github.com/shell-files/dev_highgooh.git /home/ubuntu/app && cd /home/ubuntu/app

          git fetch origin
          git reset --hard origin/dev

          cd frontend

          rm -rf dist 
          npm install
          npm run build

          cd ..

          cd /home/ubuntu/compose || git clone https://github.com/${{ github.repository }} /home/ubuntu/compose && cd /home/ubuntu/compose

          git fetch origin
          git reset --hard origin/main 

          docker compose down
          docker compose up -d